// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB98Xpd_TYn2DHuHCwXmsl2xZmzqyCyFN4',
    appId: '1:201481906388:web:bf37f711880fb909a93341',
    messagingSenderId: '201481906388',
    projectId: 'gla-connect-95c3f',
    authDomain: 'gla-connect-95c3f.firebaseapp.com',
    storageBucket: 'gla-connect-95c3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXnQDOrwjAMlC07Py0V-L3tZgY8hujQtE',
    appId: '1:201481906388:android:eac0ae3cc6a21483a93341',
    messagingSenderId: '201481906388',
    projectId: 'gla-connect-95c3f',
    storageBucket: 'gla-connect-95c3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCugHvAWMB3ik0Z1Qe0yMmRt3q3NA8faxk',
    appId: '1:201481906388:ios:9f8cc7d9bd2ee679a93341',
    messagingSenderId: '201481906388',
    projectId: 'gla-connect-95c3f',
    storageBucket: 'gla-connect-95c3f.appspot.com',
    iosClientId: '201481906388-j9vdpu6pdilehqegbk81s4pi0foapjof.apps.googleusercontent.com',
    iosBundleId: 'com.example.glaConnect',
  );
}
